### ISSUE TITLE
The order of the output

### ISSUE THREAD

**Issue by macin** [slnsys/obsidian-canvas2document#2]
Hi, this is potentially a great plugin. Great work! I am testing hit out and I faced a problem... is there a way to control the order of the cards on the final md file? I have a master node, from which all the arrows point out to the next nodes, but this main one is placed at the end of the generated doc.

**Comment by slnsys** [comment]
Obsidian canvases, of course, can have all sorts of structures, from hierarchical graphs to gigantic, non-hierarchical maps for which no order is recognizable.

The plugin always assumes the latter case at first. For this reason, navigation headings are inserted into the target document, which help to determine the order subsequently by using the normal outline view:

![image](https://github.com/slnsys/obsidian-canvas2document/assets/161649412/af48800b-91c4-40d2-8975-38e0ba7a2516)

In addition, several strategies are planned for Canvas2Document to let the user determine the order before or with the conversion:

- The nodes, cards and media relevant for the conversion could be provided with defined metadata, i.e. a tag notation in which the desired order can be specified.
- The plugin detects the cases of canvas types where there is actually a unique hierarchical structure and adheres to that structure.

**Comment by macin** [comment]
Hi @slnsys 
Thanks for reply. Maybe I am doing something incorrectly. I have a following diagram

![example](https://github.com/slnsys/obsidian-canvas2document/assets/1422747/5c871382-280c-44a5-8d63-d50d502a7aa5)

This is an automatically generated document generated by Plugin [Canvas2Document](https://github.com/slnsys/obsidian-canvas2document)



# ___noteFile from Canvas
10_Ideas/The Mediterranean breeze of Barcelona.md ^43f5df7e1b421c1b

> [!tip] link navigation from the canvas
> linking to: [[#^2e1947ede751d1c2|canvaslink]]
> linking to: [[#^f24b988c0d5b62d6|canvaslink]]
> linking to: [[#^b35626095eb073f3|canvaslink]]
> linked from: [[#^caba06b69b14c48e|canvaslink]]

 ![[10_Ideas/The Mediterranean breeze of Barcelona.md]]



# ___noteFile from Canvas
An European weekend gateway/02 The historic mystique of Prague.md ^eba81ce92cb5c925

> [!tip] link navigation from the canvas
> linked from: [[#^caba06b69b14c48e|canvaslink]]

 ![[An European weekend gateway/02 The historic mystique of Prague.md]]



# ___noteFile from Canvas
An European weekend gateway/06 Epilogue Sunday's Farewell - The Last Chapter of Barcelona trip.md ^f24b988c0d5b62d6

> [!tip] link navigation from the canvas
> linked from: [[#^43f5df7e1b421c1b|canvaslink]]

 ![[An European weekend gateway/06 Epilogue Sunday's Farewell - The Last Chapter of Barcelona trip.md]]



# ___noteFile from Canvas
An European weekend gateway/05 The Heart of Your Journey - Barcelona on Saturday.md ^2e1947ede751d1c2

> [!tip] link navigation from the canvas
> linked from: [[#^43f5df7e1b421c1b|canvaslink]]

 ![[An European weekend gateway/05 The Heart of Your Journey - Barcelona on Saturday.md]]



# ___noteFile from Canvas
An European weekend gateway/04 Arrival on Friday - The prologue of Barcelona Discovery.md ^b35626095eb073f3

> [!tip] link navigation from the canvas
> linked from: [[#^43f5df7e1b421c1b|canvaslink]]

 ![[An European weekend gateway/04 Arrival on Friday - The prologue of Barcelona Discovery.md]]



# ___noteFile from Canvas
An European weekend gateway/01 The artistic pulse of Paris.md ^6a91d501325fc935

> [!tip] link navigation from the canvas
> linked from: [[#^caba06b69b14c48e|canvaslink]]

 ![[An European weekend gateway/01 The artistic pulse of Paris.md]]



# ___noteFile from Canvas
An European weekend gateway/00 A European weekend gateway.md ^caba06b69b14c48e

> [!tip] link navigation from the canvas
> linking to: [[#^6a91d501325fc935|canvaslink]]
> linking to: [[#^43f5df7e1b421c1b|canvaslink]]
> linking to: [[#^eba81ce92cb5c925|canvaslink]]

 ![[An European weekend gateway/00 A European weekend gateway.md]]

**Comment by slnsys** [comment]
In relation to your canvas, which contains an entire article and chapters numbered by heading in a unique tree form, the result of the conversion is of course not satisfactory. A manual adjustment of the sequence / document structure via the TOC view is still necessary here. That's why the plugin inserts the "navigational headings".

The plugin's current approach assumes that a canvas can be anything, unordered. The add-on's view of the canvas data currently lacks what I would call "**topological semantics**".

There are two ways of looking at this:
1. **Topological semantics by hierarchy**: machine-readable, but due to heterogeneity with challenges in mapping to the document form.
There are defined parent/child relationships, which do not always have to be simple, directed 1:n relationships, but can morph away from  trees to arbitrary graph structures.
2. **Topological semantics by placement on the canvas**: human perception.
I.e., the information about where in the canvas an element is placed (also "top" versus "bottom") or in which order something is lined up (see "up" to "down" or LTR)

Both topological semantics will be supported by Canvas2Document through appropriate parsing strategies.

@1: A readable sequence within hierarchically subordinate elements could be achieved by means of manually edited metadata, which the user uses to determine the order before conversion.

@2: In addition, the plugin will soon be able to read different forms of hierarchical topologies and implement them in conversion.

Also check out the new release [1.1.0](https://github.com/slnsys/obsidian-canvas2document/releases/tag/1.1.0)

**Comment by macin** [comment]
Ok, I got how to manually adjust the order. Did not get it before. One feedback though: having the  "__Card from canvas" repeated multiple times in the outline is hard to undersand what each header means... did you consider putting some meaninngful content instead? Like first sentence or first X characters there? 
Now I have to manualy open each section and read first sentence to know which card that is. Not bad but maybe some improvements here would be possible

Anyway, point 2 from the above sounds super interesting,looking forward to it.

**Comment by slnsys** [comment]
> having the "__Card from canvas" repeated multiple times in the outline is hard to undersand what each header means... did you consider putting some meaninngful content instead? Like first sentence or first X characters there?

yes, that's exactly what is to come here for these "non-speaking" multiple navigational headers.

**Comment by slnsys** [comment]
done in Release 1.2.0
